unbind C-b
set -g prefix C-s
# set -g mode-mouse on
# set -g mouse-resize-pane on
set-option -g mouse on
set-option -g default-shell /bin/zsh
# set-option -g default-terminal "screen-256color"
set-option -g history-limit 30000
set-option -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# set-option -sa terminal-overrides ',xterm-256color:RGB'
# Forward extended key sequences to applications
set -s extended-keys on

# Tell tmux your outer terminal supports extended keys
# Adjust the glob to match your terminal's $TERM value
set -as terminal-features ',*alacritty*:extkeys'  # Alacritty

# Use CSI u encoding format
# set -s extended-keys-format csi-u

# Map Shift+Enter explicitly inside tmux
bind-key -n S-Enter send-keys Escape "[13;2u"

set -g extended-keys on
set -g extended-keys-format csi-u

# Open new splits and windows in the same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

## toggle mouse mode
bind-key m set -g mouse on \; display "Mouse ON"
bind-key M set -g mouse off \; display "Mouse OFF"

set-option -g status-left-length 50
set-option -s escape-time 00

set-option -g focus-events on

# set -g pane-border-fg colour0
# set -g pane-active-border-fg colour1
set -g status-bg black
set -g status-fg white

# set -g window-style 'fg=black,bg=white'
# set -g window-active-style 'fg=black,bg=white'

unbind C-l

# bind -n C-h select-pane -L
# bind -n C-j select-pane -D
# bind -n C-k select-pane -U
# bind -n C-l select-pane -R

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

bind -r C-j resize-pane -D 20
bind -r C-k resize-pane -U 20
bind -r C-h resize-pane -L 20
bind -r C-l resize-pane -R 20
bind -r P paste-buffer
setw -g mode-keys vi

#PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @vim_navigator_prefix_mapping_clear_screen ""

run '~/.tmux/plugins/tpm/tpm'
